#ifndef buzzer_music_h
#define buzzer_music_h

#include <Arduino.h>

void c_low_4();
void d_low_4();
void e_low_4();
void f_low_4();
void g_low_4();
void a_low_4();
void b_low_4();
void c_high_4();
void d_high_4();
void e_high_4();
void f_high_4();
void g_high_4();
void a_high_4();
void b_high_4();
void c_low_sharp_4();
void d_low_sharp_4();
void f_low_sharp_4();
void g_low_sharp_4();
void a_low_sharp_4();
void c_high_sharp_4();
void d_high_sharp_4();
void f_high_sharp_4();
void g_high_sharp_4();
void a_high_sharp_4();
void c_low_8();
void d_low_8();
void e_low_8();
void f_low_8();
void g_low_8();
void a_low_8();
void b_low_8();
void c_high_8();
void d_high_8();
void e_high_8();
void f_high_8();
void g_high_8();
void a_high_8();
void b_high_8();
void c_low_sharp_8();
void d_low_sharp_8();
void f_low_sharp_8();
void g_low_sharp_8();
void a_low_sharp_8();
void c_high_sharp_8();
void d_high_sharp_8();
void f_high_sharp_8();
void g_high_sharp_8();
void a_high_sharp_8();
void c_low_16();
void d_low_16();
void e_low_16();
void f_low_16();
void g_low_16();
void a_low_16();
void b_low_16();
void c_high_16();
void d_high_16();
void e_high_16();
void f_high_16();
void g_high_16();
void a_high_16();
void b_high_16();
void c_low_sharp_16();
void d_low_sharp_16();
void f_low_sharp_16();
void g_low_sharp_16();
void a_low_sharp_16();
void c_high_sharp_16();
void d_high_sharp_16();
void f_high_sharp_16();
void g_high_sharp_16();
void a_high_sharp_16();

#endif